package com.openclassrooms.magicgithub.api

import com.openclassrooms.magicgithub.model.User

class FakeApiService : ApiService {
    private val _users = FakeApiServiceGenerator.FAKE_USERS

    /**
     * Return a list of [User]
     * Those users must be generated by [FakeApiServiceGenerator]
     */
    override fun getUsers(): List<User> {
        return _users.toList()
    }

    /**
     * Generate a random [User] and add it [FakeApiService.users] list.
     * This user must be get from the [FakeApiServiceGenerator.FAKE_USERS_RANDOM] list.
     */
    override fun addRandomUser() {
        val Users = FakeApiServiceGenerator.FAKE_USERS_RANDOM
        val randomUser = Users.random()
        _users.add(randomUser)
    }

    override fun swapUsers(fromPosition: Int, toPosition: Int) {
        val temp = _users[fromPosition]
        _users[fromPosition] = _users[toPosition]
        _users[toPosition] = temp
    }

    /**
     * Delete a [User] from the [FakeApiService.users] list.
     */
    override fun deleteUser(user: User) {
        _users.remove(user)
    }
}